name: arrow2dart
version: 0.1.0
author: Emil Persson <emil.n.persson@gmail.com>
description: Compile Arrow to Dart

dependencies:
  arrow_ast: ^0.1.0
  arrowfmt: ^0.1.0
  analyzer: ^0.27.0
  args: ^0.13.2
  dart_style: ^0.2.2

executables:
  - arrow2dart

dependency_overrides:
  arrow_ast:
    path: ../ast
  arrowfmt:
    path: ../arrowfmt